### ISSUE TITLE
Как прикрутить  ru-server к couchpotato?

### ISSUE THREAD

**Issue by c4uran** [leugenea/cp-ru-server#3]
Поднял ваш контейнер в докере только не понял как его подключить к couchpotato по ссылке я так и не понял откуда взять инфо для полей Pass Key и Username поэтому оставил их пустыми, только внутренний сервер с портом заполнил и когда начинаю поиск фильма на выходе в couchpotato такой отлуп:

```
03-21 18:40:41 INFO
[ie.providers.info.omdbapi] Found: Mute (2018)
03-21 18:40:41 ERROR
[to.core.media._base.media] Failed restatus: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/media/_base/media/main.py", line 514, in restatus profile = db.get('id', m['profile_id']) File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner res = f(*args, **kwargs) File "/app/couchpotato/libs/CodernityDB/database.py", line 946, in get raise RecordDeleted("Deleted") RecordDeleted: Deleted
03-21 18:40:41 INFO
[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt1464763/, data: []
03-21 18:40:41 ERROR
[ couchpotato.core.event] Error in event "movie.searcher.single", that wasn't caught: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/event.py", line 15, in runHandler return handler(*args, **kwargs) File "/app/couchpotato/couchpotato/core/media/movie/searcher.py", line 160, in single profile = db.get('id', movie['profile_id']) File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner res = f(*args, **kwargs) File "/app/couchpotato/libs/CodernityDB/database.py", line 946, in get raise RecordDeleted("Deleted") RecordDeleted: Deleted encoding=UTF-8 debug=False args=['--config_file=/config/config.ini', '--data_dir=/config/data'] app_dir=/app/couchpotato data_dir=/config/data desktop=None options=Namespace(config_file='/config/config.ini', console_log=False, daemon=False, data_dir='/config/data', debug=False, pid_file='/config/data/couchpotato.pid', quiet=False)
```

**Comment by leugenea** [comment]
Этот проект был сделан, когда Jackett не поддерживал Rutracker, но теперь он его поддерживает. Советую использовать его.
Возможно, я через какое-то время посмотрю на проблему, но сейчас времени нет.

**Comment by c4uran** [comment]
Простите, а какой проект его использует?

**Comment by leugenea** [comment]
Я не уверен, что понял вопрос. Какой проект и кого использует?
